name: Selenium Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # daily at 2 AM UTC

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Selenium dependencies
      run: |
        npm install selenium-webdriver chromedriver geckodriver jest @types/selenium-webdriver jest-html-reporters

    - name: Setup Chrome
      if: matrix.browser == 'chrome'
      uses: browser-actions/setup-chrome@latest

    - name: Setup Firefox
      if: matrix.browser == 'firefox'
      uses: browser-actions/setup-firefox@latest

    - name: Run Selenium tests
      env:
        BROWSER: ${{ matrix.browser }}
        HEADLESS: true
        SELENIUM_BASE_URL: https://mikmikcodes.github.io/formula-calc/
      run: npm run test:selenium

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: selenium-test-results-${{ matrix.browser }}
        path: |
          selenium/reports/
          selenium/screenshots/
        retention-days: 30

    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: selenium-html-report-${{ matrix.browser }}
        path: selenium/reports/selenium-test-report.html
        retention-days: 30

  test-summary:
    needs: selenium-tests
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Download test artifacts
      uses: actions/download-artifact@v4

    - name: Test Summary
      run: |
        echo "## Selenium Test Results 🧪" >> $GITHUB_STEP_SUMMARY
        echo "Tests completed for Chrome and Firefox browsers" >> $GITHUB_STEP_SUMMARY
        echo "Check the artifacts for detailed reports" >> $GITHUB_STEP_SUMMARY
